name: Release Notification

on:
  release:
    types: [published]

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: support@dlplace.eu
        password: 'FzwyE*ss1e667U8f'
        subject: Une nouvelle version est disponible!
        body: |
          A new release has been published on the repository.
          Tag: ${{ github.event.release.tag_name }}
          Name: ${{ github.event.release.name }}
          Description: ${{ github.event.release.body }}
        to: 'alecalec147@gmail.com, yehadjialexis@gmal.com'
        from: support@dlplace.eu
